name: Write my yaml file 

on:
  push:
     branches:
       - main


permissions:
  id-token: write # this is for oicd token
  contents: read # this is for github can read your repo 


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: checkout code
      - uses: actions/checkout@v4 # copy all the code from my repo to ubuntu machine 

      - name: install nodejs
      - uses: actions/setup-node@v4    # install node.js in ubuntu machine 
        with:
          node-version: 24  # with version 24
          cache: npm         # and also cache npm 


      - name: install dependencies
        run: npm ci

      - name: build react app
        run: npm run build
        
      




